"""Add contract email status fields to Provider model

Revision ID: 12a4b3c56789
Revises: 18df4deca62b
Create Date: 2025-05-17 14:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12a4b3c56789'
down_revision = '18df4deca62b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_email_sent', sa.Boolean(), nullable=True, default=False))
        batch_op.add_column(sa.Column('contract_email_sent_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('contract_email_sent_to', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('contract_email_tracking_id', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('contract_email_tracking_id')
        batch_op.drop_column('contract_email_sent_to')
        batch_op.drop_column('contract_email_sent_at')
        batch_op.drop_column('contract_email_sent')
    # ### end Alembic commands ###