"""Add contract file path columns to Provider model

Revision ID: 18df4deca62b
Revises: 
Create Date: 2025-04-05 10:48:10.469208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18df4deca62b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contract_docx', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('contract_pdf', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.drop_column('contract_pdf')
        batch_op.drop_column('contract_docx')
    # ### end Alembic commands ###
